<?xml version="1.0"?>
<package format="3">
  <name>go2_config</name>
  <version>0.1.0</version>
  <description>Go2 Config Package</description>

  <maintainer email="anujjain.dev@gmail.com">Anuj Jain</maintainer>
  <author>Anuj Jain</author>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>launch_ros</build_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>champ_bringup</exec_depend>
  <exec_depend>champ_gazebo</exec_depend>
  <exec_depend>champ_navigation</exec_depend>
  <exec_depend>go2_description</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>rtabmap_launch</exec_depend>
  <exec_depend>rtabmap_stack_env</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
